# Generated by Django 6.1 on 2026-08-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
