# Generated by Django 6.1 on 2026-08-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_shortlink_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='slug',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
